### ISSUE TITLE
 FrontConf Experience 2024 — Link quebrado

### ISSUE THREAD

**Issue by imteekay** [Abacatinhos/eventos-tech-brasil#152]
Parece que o link do evento "FrontConf Experience 2024 - Mergo" está quebrado. Ele é redirecionado para esse link https://www.mergo.com.br/eventos/frontconfxp/ e assim está a página.

![Screenshot 2024-02-29 at 15 30 06](https://github.com/Abacatinhos/eventos-tech-brasil/assets/5835798/fe904bcb-ccbb-4eca-9682-bf79abcf0968)

Sabe se o evento ainda irá acontecer?

**Comment by stephan-lopes** [comment]
Opa, @imteekay

Acredito que foi cancelado sim. Tentei buscar alguma informação a respeito, mas achei apenas no google, com trecho de destaque (provavelmente removeram depois do site, pois a página estava com link quebrado, como informado por você).

<img width="683" alt="Screenshot 2024-03-01 at 19 29 59" src="https://github.com/Abacatinhos/eventos-tech-brasil/assets/40838038/c36d1831-000c-4be4-8afe-5c29fd9caa6c">

Vou abrir um PR para remover ele do README, no mês e data em que estavam marcados, e movê-lo para TBA.

Obrigado por compartilhar sua observação 💚

**Comment by imteekay** [comment]
Muito obrigado @stephan-lopes! Eu acabei de mandar uma mensagem pra eles, pra poder confirmar ou se vão abrir no futuro, ainda em 2024. Se abrir, eu posso abrir um PR adicionando novamente com as informações corretas.
