### ISSUE TITLE
[Evento]: Java Day

### ISSUE THREAD

**Issue by jocarsbarsa** [Abacatinhos/eventos-tech-brasil#231]
### Evento

Java Day

### Site

https://javanoroeste.com.br/javanoroeste/javaday_riopreto/

### Tipo

Presencial

### local

São José do Rio Preto - SP

### Mês

AGOSTO

### Dia

31

**Comment by stephan-lopes** [comment]
Opa! Fechando a issue por já ter o evento adicionado no commit https://github.com/Abacatinhos/eventos-tech-brasil/commit/afd8086b2df28dfb94e0a08245efee6fbf9258cc. Obrigado pela contribuição!
